import logging

from dotenv import load_dotenv
from livekit.agents import (
    Agent,
    AgentSession,
    JobContext,
    JobProcess,
    MetricsCollectedEvent,
    RoomInputOptions,
    WorkerOptions,
    cli,
    metrics,
    tokenize,
    function_tool,
    RunContext
)
from livekit.plugins import murf, silero, google, cartesia, noise_cancellation
from livekit.plugins.turn_detector.multilingual import MultilingualModel
import json
import os
from datetime import datetime

logger = logging.getLogger("agent")

load_dotenv(".env.local")


class Assistant(Agent):
    def __init__(self) -> None:
        # Load past context
        context_summary = "This is the first check-in."
        try:
            if os.path.exists("wellness_log.json"):
                with open("wellness_log.json", "r") as f:
                    logs = json.load(f)
                    if logs:
                        last_entry = logs[-1]
                        # Handle potential missing keys in old logs if any
                        mood = last_entry.get('mood', 'unknown')
                        objs = last_entry.get('objectives', [])
                        objs_str = ', '.join(objs) if objs else 'none'
                        context_summary = f"Previous check-in on {last_entry.get('timestamp', 'unknown')}: Mood was {mood}, Goals were {objs_str}."
        except Exception as e:
            logger.error(f"Failed to load context: {e}")

        super().__init__(
            instructions=f"""You are a supportive, grounded Health & Wellness Voice Companion.
            Your goal is to check in with the user about their mood and intentions for the day.
            
            Context from previous session: {context_summary}
            
            Structure your conversation:
            1. Ask about their mood and energy levels today.
            2. Ask about 1-3 simple, actionable objectives for the day.
            3. Offer brief, grounded advice or encouragement (non-medical).
            4. Recap their mood and objectives to confirm.
            5. Once confirmed, use the save_wellness_log tool to save the entry.
            
            Be warm, empathetic, and concise. Avoid medical diagnoses.""",
        )

    @function_tool
    async def save_wellness_log(
        self,
        context: RunContext,
        mood: str,
        objectives: list[str],
        summary: str
    ):
        """Save the daily wellness check-in to a JSON log.
        
        Args:
            mood: User's self-reported mood and energy level.
            objectives: List of 1-3 goals/intentions for the day.
            summary: A brief, supportive summary sentence generated by the agent.
        """
        entry = {
            "timestamp": datetime.now().isoformat(),
            "mood": mood,
            "objectives": objectives,
            "summary": summary
        }
        
        filename = "wellness_log.json"
        logs = []
        if os.path.exists(filename):
            try:
                with open(filename, 'r') as f:
                    logs = json.load(f)
                    if not isinstance(logs, list):
                        logs = []
            except:
                logs = []
        
        logs.append(entry)
        
        with open(filename, 'w') as f:
            json.dump(logs, f, indent=2)
            
        return "I've saved your check-in. Have a wonderful day!"


def prewarm(proc: JobProcess):
    proc.userdata["vad"] = silero.VAD.load()


async def entrypoint(ctx: JobContext):
    # Logging setup
    # Add any other context you want in all log entries here
    ctx.log_context_fields = {
        "room": ctx.room.name,
    }

    # Set up a voice AI pipeline using OpenAI, Cartesia, AssemblyAI, and the LiveKit turn detector
    session = AgentSession(
        # Speech-to-text (STT) is your agent's ears, turning the user's speech into text that the LLM can understand
        # See all available models at https://docs.livekit.io/agents/models/stt/
        stt=cartesia.STT( model="ink-whisper"), #this can be changed to elevenlabs/deepgram/
        # A Large Language Model (LLM) is your agent's brain, processing user input and generating a response
        # See all available models at https://docs.livekit.io/agents/models/llm/
        llm=google.LLM(
                model="gemini-3-pro-preview",
            ),
        # Text-to-speech (TTS) is your agent's voice, turning the LLM's text into speech that the user can hear
        # See all available models as well as voice selections at https://docs.livekit.io/agents/models/tts/
        tts=murf.TTS(
                voice="en-US-matthew", 
                style="Conversation",
                tokenizer=tokenize.basic.SentenceTokenizer(min_sentence_len=2),
                text_pacing=True
            ),
        # VAD and turn detection are used to determine when the user is speaking and when the agent should respond
        # See more at https://docs.livekit.io/agents/build/turns
        turn_detection=MultilingualModel(),
        vad=ctx.proc.userdata["vad"],
        # allow the LLM to generate a response while waiting for the end of turn
        # See more at https://docs.livekit.io/agents/build/audio/#preemptive-generation
        preemptive_generation=True,
    )

    # To use a realtime model instead of a voice pipeline, use the following session setup instead.
    # (Note: This is for the OpenAI Realtime API. For other providers, see https://docs.livekit.io/agents/models/realtime/))
    # 1. Install livekit-agents[openai]
    # 2. Set OPENAI_API_KEY in .env.local
    # 3. Add `from livekit.plugins import openai` to the top of this file
    # 4. Use the following session setup instead of the version above
    # session = AgentSession(
    #     llm=openai.realtime.RealtimeModel(voice="marin")
    # )

    # Metrics collection, to measure pipeline performance
    # For more information, see https://docs.livekit.io/agents/build/metrics/
    usage_collector = metrics.UsageCollector()

    @session.on("metrics_collected")
    def _on_metrics_collected(ev: MetricsCollectedEvent):
        metrics.log_metrics(ev.metrics)
        usage_collector.collect(ev.metrics)

    async def log_usage():
        summary = usage_collector.get_summary()
        logger.info(f"Usage: {summary}")

    ctx.add_shutdown_callback(log_usage)

    # # Add a virtual avatar to the session, if desired
    # # For other providers, see https://docs.livekit.io/agents/models/avatar/
    # avatar = hedra.AvatarSession(
    #   avatar_id="...",  # See https://docs.livekit.io/agents/models/avatar/plugins/hedra
    # )
    # # Start the avatar and wait for it to join
    # await avatar.start(session, room=ctx.room)

    # Start the session, which initializes the voice pipeline and warms up the models
    await session.start(
        agent=Assistant(),
        room=ctx.room,
        room_input_options=RoomInputOptions(
            # For telephony applications, use `BVCTelephony` for best results
            noise_cancellation=noise_cancellation.BVC(),
        ),
    )

    # Join the room and connect to the user
    await ctx.connect()


if __name__ == "__main__":
    cli.run_app(WorkerOptions(entrypoint_fnc=entrypoint, prewarm_fnc=prewarm))
